using System;
using System.Collections.Generic;

namespace TokenManager
{
	public static class Constants
	{
		public const string TokenCollectionStandardValuesId = "{D627C02A-7DD7-4FA6-A1F5-1FBFD869B6F2}";
		public const string TokenFieldId = "{273E8C26-5BF0-4DC1-8430-BDB5C2665853}";
		public const string TokenCollectionCategoryFieldId = "{81941697-38C9-4B03-A045-EB065A690B9E}";

		public const string TokenCollectionCoreTemplateId = "{D31BC00A-F078-4D5D-A93F-CD0E5C850237}";
		public const string TokenTemplateId = "{87BFAA2C-2E2F-42C6-A135-9F2AE7D32807}";

		public const string TokenCollectionFolderTemplateId = "{1068A0B2-91C4-44F2-A7E4-62CE737C595D}";

		public const string TokenTemplateBaseId = "{13632250-8E53-4A36-9E9B-B1DC6452D4C5}";
		public const string TokenCollectionTemplateBaseId = "{4645BD90-1874-4456-8338-D7440C20A477}";

		public const string TokenRootTemplateId = "{D48A879D-2142-4DFB-A773-C8AF686AE779}";
		public const string TokenStripOuterPTagsFieldId = "{01038533-5010-4BD2-A2E5-C08D263CCC7A}";

		public const string TokenDividerId = "{110669A7-8A48-478F-AC7B-7D8AEC7F8F7D}";
		public const string TokenButtonId = "{AFA8831E-F5DD-4DF2-A96A-8E223A68D4EB}";

		public static readonly Guid IdGenerationId = new Guid("{9068084E-CB06-450D-90AC-DB9CCE2B2F0D}");
	#region Token Types
	//Method Token
	public const string TokenMethodCollectionTemplateId = "{BB9FBFD1-1C36-4B1C-95C1-E02DEA5B2C8B}";
		//Shared Link Token
		public const string TokenSharedLinkCollectionTemplateId = "{5273E95E-6857-4CEE-900C-ABCA5EED44C3}";
		public const string TokenSharedLinkTemplateId = "{98850963-EC5A-4A3C-A292-78103D3AC6E9}";
		//Rendering Token
		public const string TokenRenderingCollectionTemplateId = "{A4875CC7-BACE-4F5A-AE35-B9C5502DA26A}";
		public const string TokenRenderingTokenTemplateId = "{B5C519E3-9EEE-4914-9FCE-51B0B0800697}";
		//Rules Token
		public const string TokenRulesCollectionTemplateId = "{147C5339-DB74-413F-A749-AE4C29B7C1F0}";
		public const string TokenRulesTokenTemplateId = "{7D6A72CC-D346-43D2-A279-EF6CA27BCF31}";
		//General Token
		public const string TokenCollectionTemplateId = "{B49DB165-E3A5-45D1-B4E7-F5E707B73C9E}";

		#endregion

		public static class Core
		{
			public const string RteParent = "{7E9759CA-21FC-4091-ABE1-931D6BCA4615}";
			public const string ButtonTemplate = "{3C8BD8A1-280B-4278-BB8B-21FA3B87AF0F}";
		}
		public static readonly HashSet<string> BinaryBlacklist = new HashSet<string>(new []{
			"Antlr3.Runtime",
			"ComponentArt.Web.UI",
			"DotNetOpenAuth",
			"EcmaScript.NET",
			"Facebook",
			"FacebookAPI",
			"Google.Apis.Authentication.OAuth2",
			"Google.Apis",
			"Google.Apis.Plus.v1",
			"Hammock.ClientProfile",
			"HtmlAgilityPack",
			"ICSharpCode.SharpZipLib",
			"Iesi.Collections",
			"ITHit.WebDAV.Server",
			"Lucene.Net.Contrib.Analyzers",
			"Lucene.Net.Contrib.Core",
			"Lucene.Net.Contrib.FastVectorHighlighter",
			"Lucene.Net.Contrib.Highlighter",
			"Lucene.Net.Contrib.Memory",
			"Lucene.Net.Contrib.Queries",
			"Lucene.Net.Contrib.Regex",
			"Lucene.Net.Contrib.SimpleFacetedSearch",
			"Lucene.Net.Contrib.Snowball",
			"Lucene.Net.Contrib.SpellChecker",
			"Lucene.Net",
			"MarkdownSharp",
			"Microsoft.AspNet.WebApi.Extensions.Compression.Server",
			"Microsoft.Extensions.DependencyInjection.Abstractions",
			"Microsoft.Extensions.DependencyInjection",
			"Microsoft.OData.Core",
			"Microsoft.OData.Edm",
			"Microsoft.Practices.ServiceLocation",
			"Microsoft.Spatial",
			"Microsoft.Web.Infrastructure",
			"MongoDB.Bson",
			"MongoDB.Driver",
			"Mvp.Xml",
			"Netbiscuits.OnPremise",
			"Newtonsoft.Json",
			"OAuthLinkedIn",
			"protobuf-net",
			"RadEditor.Net2",
			"RazorGenerator.Mvc",
			"Sitecore.Abstractions",
			"Sitecore.Analytics.Aggregation",
			"Sitecore.Analytics.Automation.Aggregation",
			"Sitecore.Analytics.Automation",
			"Sitecore.Analytics.Automation.MongoDB",
			"Sitecore.Analytics.Core",
			"Sitecore.Analytics.DataAccess",
			"Sitecore.Analytics",
			"Sitecore.Analytics.Model",
			"Sitecore.Analytics.MongoDB",
			"Sitecore.Analytics.OmniChannel",
			"Sitecore.Analytics.Outcome",
			"Sitecore.Analytics.Processing",
			"Sitecore.Analytics.RobotDetection",
			"Sitecore.Analytics.Sql",
			"Sitecore.Apps.Loader",
			"Sitecore.Buckets.Client",
			"Sitecore.Buckets",
			"Sitecore.CES.DeviceDetection",
			"Sitecore.CES.DeviceDetection.Rules",
			"Sitecore.CES",
			"Sitecore.CES.GeoIp",
			"Sitecore.CES.GeoIp.LegacyLocation",
			"Sitecore.Cintel.Client",
			"Sitecore.Cintel",
			"Sitecore.Client",
			"Sitecore.Client.LicenseOptions",
			"Sitecore.Cloud.Nexus",
			"Sitecore.Cloud.RestClient",
			"Sitecore.Commerce",
			"Sitecore.Commerce.ExperienceAnalytics",
			"Sitecore.Commerce.ExperienceProfile",
			"Sitecore.ContentSearch.Analytics.Client",
			"Sitecore.ContentSearch.Analytics",
			"Sitecore.ContentSearch.Azure",
			"Sitecore.ContentSearch.Client",
			"Sitecore.ContentSearch",
			"Sitecore.ContentSearch.Linq",
			"Sitecore.ContentSearch.Linq.Lucene",
			"Sitecore.ContentSearch.Linq.Solr",
			"Sitecore.ContentSearch.LuceneProvider",
			"Sitecore.ContentSearch.SolrProvider",
			"Sitecore.ContentTesting",
			"Sitecore.ContentTesting.Intelligence",
			"Sitecore.ContentTesting.Model",
			"Sitecore.ContentTesting.Mvc",
			"Sitecore.ControlPanel",
			"Sitecore.ExperienceAnalytics.Aggregation",
			"Sitecore.ExperienceAnalytics.Api",
			"Sitecore.ExperienceAnalytics.Client",
			"Sitecore.ExperienceAnalytics.Core",
			"Sitecore.ExperienceAnalytics",
			"Sitecore.ExperienceAnalytics.ReAggregation",
			"Sitecore.ExperienceAnalytics.Reduce",
			"Sitecore.ExperienceContentManagement.Administration",
			"Sitecore.ExperienceEditor",
			"Sitecore.ExperienceEditor.Speak",
			"Sitecore.ExperienceEditor.Speak.Ribbon",
			"Sitecore.ExperienceExplorer.Business",
			"Sitecore.ExperienceExplorer.Web",
			"Sitecore.FXM.Client",
			"Sitecore.FXM",
			"Sitecore.FXM.Service",
			"Sitecore.FXM.Speak",
			"Sitecore.ItemWebApi",
			"Sitecore.Kernel",
			"Sitecore.LaunchPad",
			"Sitecore.ListManagement.Analytics",
			"Sitecore.ListManagement.Client",
			"Sitecore.ListManagement.ContentSearch",
			"Sitecore.ListManagement",
			"Sitecore.ListManagement.Services",
			"Sitecore.Logging.Client",
			"Sitecore.Logging",
			"Sitecore.Marketing.Campaigns.Client",
			"Sitecore.Marketing.Campaigns.Services",
			"Sitecore.Marketing.Client",
			"Sitecore.Marketing.Core",
			"Sitecore.Marketing.Definitions.MarketingAssets.Repositories",
			"Sitecore.Marketing",
			"Sitecore.Marketing.Search",
			"Sitecore.Marketing.Taxonomy",
			"Sitecore.Mvc.Analytics",
			"Sitecore.Mvc.DeviceSimulator",
			"Sitecore.Mvc",
			"Sitecore.Mvc.ExperienceEditor",
			"Sitecore.Nexus",
			"Sitecore.NVelocity",
			"Sitecore.Oracle",
			"Sitecore.PathAnalyzer.Client",
			"Sitecore.PathAnalyzer",
			"Sitecore.PathAnalyzer.Services",
			"Sitecore.Publishing.WebDeploy",
			"Sitecore.Security.AntiCsrf",
			"Sitecore.SegmentBuilder",
			"Sitecore.SequenceAnalyzer",
			"Sitecore.Services.Client",
			"Sitecore.Services.Core",
			"Sitecore.Services.Infrastructure",
			"Sitecore.Services.Infrastructure.Sitecore",
			"Sitecore.SessionProvider",
			"Sitecore.SessionProvider.Memory",
			"Sitecore.SessionProvider.MongoDB",
			"Sitecore.SessionProvider.Redis",
			"Sitecore.SessionProvider.Sql",
			"Sitecore.Shell.MarketingAutomation",
			"Sitecore.Social.Api",
			"Sitecore.Social.Client.Api",
			"Sitecore.Social.Client.Common",
			"Sitecore.Social.Client",
			"Sitecore.Social.Client.Domain",
			"Sitecore.Social.Client.Mvc",
			"Sitecore.Social.Client.PublishingService",
			"Sitecore.Social.Client.Speak",
			"Sitecore.Social.Configuration",
			"Sitecore.Social",
			"Sitecore.Social.Domain",
			"Sitecore.Social.ExperienceProfile.Client",
			"Sitecore.Social.Facebook.Api",
			"Sitecore.Social.Facebook.Client",
			"Sitecore.Social.Facebook.Client.Mvc",
			"Sitecore.Social.Facebook",
			"Sitecore.Social.GooglePlus.Client",
			"Sitecore.Social.GooglePlus.Client.Mvc",
			"Sitecore.Social.GooglePlus",
			"Sitecore.Social.Infrastructure",
			"Sitecore.Social.Infrastructure.Logging",
			"Sitecore.Social.Installation",
			"Sitecore.Social.Klout.Api",
			"Sitecore.Social.Klout.Client",
			"Sitecore.Social.LinkedIn.Client",
			"Sitecore.Social.LinkedIn.Client.Mvc",
			"Sitecore.Social.LinkedIn",
			"Sitecore.Social.NetworkProviders",
			"Sitecore.Social.SitecoreAccess",
			"Sitecore.Social.SocialMarketer.Api",
			"Sitecore.Social.SocialMarketer.Client",
			"Sitecore.Social.SocialMarketer",
			"Sitecore.Social.Twitter.Api",
			"Sitecore.Social.Twitter.Client",
			"Sitecore.Social.Twitter.Client.Mvc",
			"Sitecore.Social.Twitter",
			"Sitecore.Speak.Applications",
			"Sitecore.Speak.Client",
			"Sitecore.Speak.Components",
			"Sitecore.Speak.Components.Guidance",
			"Sitecore.Speak.Components.Web",
			"Sitecore.Speak.ItemWebApi",
			"Sitecore.Speak.Web",
			"Sitecore.Update",
			"Sitecore.Web",
			"Sitecore.Xdb.Client",
			"Sitecore.Xdb.Configuration",
			"Sitecore.Zip",
			"SolrNet",
			"StackExchange.Redis.StrongName",
			"Stimulsoft.Base",
			"Stimulsoft.Database",
			"Stimulsoft.Report",
			"Stimulsoft.Report.Web",
			"Stimulsoft.Report.WebDesign",
			"System.IdentityModel.Tokens.Jwt",
			"System.Net.Http.Extensions.Compression.Core",
			"System.Net.Http.Formatting",
			"System.Web.Cors",
			"System.Web.Helpers",
			"System.Web.Http.Cors",
			"System.Web.Http",
			"System.Web.Http.WebHost",
			"System.Web.Mvc",
			"System.Web.OData",
			"System.Web.Optimization",
			"System.Web.Razor",
			"System.Web.WebPages.Deployment",
			"System.Web.WebPages",
			"System.Web.WebPages.Razor",
			"Telerik.Web.UI",
			"Telerik.Web.UI.Skins",
			"TweetSharp",
			"WebActivatorEx",
			"WebGrease",
			"Yahoo.Yui.Compressor"}); 
	}
}
